services:
  api:
    image: ${IMAGE_REPO:-shvin/telemetry-api}:${IMAGE_TAG:-v0.8.10-golden}
    environment:
      TELEMETRY_DLQ_DIR: ${TELEMETRY_DLQ_DIR:-/tmp/dlq}
      TELEMETRY_SEED_KEYS: ${TELEMETRY_SEED_KEYS:-TEST_ADMIN_KEY,DEV_ADMIN_KEY_5a8f9ffdc3}
      FEATURE_SOURCES: ${FEATURE_SOURCES:-1}
      FEATURE_UDP_HEAD: ${FEATURE_UDP_HEAD:-0}
  
  udp-ingestor:
    profiles: ["disabled"]
