version: '3.8'

services:
  api:
    build: .
    env_file: .env
    environment:
      - APP_VERSION=0.8.0
      - DOCKERHUB_TAG=0.8.0
      - GEOIP_CITY_DB=/data/geo/GeoLite2-City.mmdb
      - GEOIP_ASN_DB=/data/geo/GeoLite2-ASN.mmdb
      - TI_PATH=/data/ti/indicators.txt
      - ENRICH_ENABLE_GEOIP=true
      - ENRICH_ENABLE_ASN=true
      - ENRICH_ENABLE_TI=true
      - EXPORT_ELASTIC_ENABLED=false
      - EXPORT_SPLUNK_ENABLED=false
      - DEMO_MODE=true
      - DEMO_EPS=50
      - DEMO_DURATION_SEC=120
      - DEMO_VARIANTS=netflow,zeek
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/v1/health')"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./geo:/data/geo:ro
      - ./ti:/data/ti:ro
