version: "3.9"
services:
  api-core:
    build: .
    image: shvin/telemetry-api:golden
    container_name: api-core
    environment:
      - APP_PORT=80
      - APP_VERSION=0.8.5
      - SQLITE_PATH=/data/telemetry.db
      - GEOIP_CITY_DB=/data/geo/GeoLite2-City.mmdb
      - GEOIP_ASN_DB=/data/geo/GeoLite2-ASN.mmdb
      - THREATLIST_CSV=/data/ti/indicators.txt
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=text
      - HTTP_LOG_ENABLED=true
      - HTTP_LOG_SAMPLE_RATE=0.1
      - HTTP_LOG_EXCLUDE_PATHS=/v1/metrics,/v1/system,/v1/logs/tail,/v1/admin/requests
      - REDACT_HEADERS=authorization,x-api-key
      - REDACT_FIELDS=password,token
      - ADMISSION_HTTP_ENABLED=true
      - HTTP_IP_ALLOWLIST_ENABLED=true
      - HTTP_TRUST_XFF=true
      - TRUST_PROXY=false
      - MAX_BATCH_BYTES=5242880
      - MAX_RECORDS=10000
      - RATE_LIMIT_PER_MIN=600
      - BOOTSTRAP_TENANT_ID=default
      - BOOTSTRAP_ADMIN_API_KEY=DEV_ADMIN_KEY_5a8f9ffdc3
    ports:
      - "80:80"
    volumes:
      - dbdata:/data
      - ./geo:/data/geo:ro
      - ./ti:/data/ti:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import time,urllib.request; import sys; import urllib.error; url='http://localhost:80/v1/health'; urllib.request.urlopen(url, timeout=2); sys.exit(0)"]
      interval: 5s
      timeout: 4s
      retries: 20
      start_period: 10s

  udp-head:
    build: ./services/udp-head
    container_name: udp-head
    environment:
      - UDP_BIND=0.0.0.0
      - UDP_PORT=2055
      - ALLOWLIST_CIDRS=
      - RATE_PER_MIN=60000
      - API_URL=http://api-core:80/v1/ingest/netflow
      - API_KEY=${API_KEY}
      - SOURCE_ID=udp-head-01
    ports:
      - "2055:2055/udp"
    depends_on:
      - api-core
    restart: unless-stopped

volumes:
  dbdata:
