version: '3.8'

services:
  api:
    image: ${API_IMAGE:-telemetry-api:latest}
    env_file: .env
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/v1/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ./data:/data:ro
    networks:
      - telemetry_network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - telemetry_network

volumes:
  caddy_data:
  caddy_config:

networks:
  telemetry_network:
    driver: bridge
