services:
  api:
    build: .
    environment:
      - APP_VERSION=0.8.0
      - DOCKERHUB_TAG=0.8.0
      - GEOIP_CITY_DB=/data/geo/GeoLite2-City.mmdb
      - GEOIP_ASN_DB=/data/geo/GeoLite2-ASN.mmdb
      - TI_PATH=/data/ti/indicators.txt
      - ENRICH_ENABLE_GEOIP=true
      - ENRICH_ENABLE_ASN=true
      - ENRICH_ENABLE_TI=true
      - EXPORT_ELASTIC_ENABLED=false
      - EXPORT_SPLUNK_ENABLED=false
      - DEMO_MODE=true
      - DEMO_EPS=50
      - DEMO_DURATION_SEC=120
      - DEMO_VARIANTS=netflow,zeek
      # Structured Logging Configuration
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - LOG_FORMAT=text
      - HTTP_LOG_ENABLED=true
      - HTTP_LOG_SAMPLE_RATE=0.1
      - HTTP_LOG_EXCLUDE_PATHS=/v1/metrics,/v1/system,/v1/logs/tail,/v1/admin/requests
      - REDACT_HEADERS=authorization,x-api-key
      - REDACT_FIELDS=password,token
      - ADMIN_AUDIT_MAX=1000
      - ADMIN_AUDIT_TTL_MINUTES=60
      - ADMIN_SHOW_LOG_TAIL=false
    ports:
      - "80:80"
      - "3000:3000"
    healthcheck:
      test: ["CMD", "python", "-c", "import time,urllib.request; 
import sys
import urllib.error
url='http://localhost:80/v1/health'
try:
    urllib.request.urlopen(url, timeout=2)
    sys.exit(0)
except Exception:
    sys.exit(1)"]
      interval: 5s
      timeout: 4s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./geo:/data/geo:ro
      - ./ti:/data/ti:ro
