services:
  telemetry-api:
    image: shvin/telemetry-api:golden
    # If building from source, use:
    # build: ../../
    container_name: telemetry-api
    environment:
      - API_KEYS=TEST_KEY
      - LOG_LEVEL=info
      - RETENTION_DAYS=7
      - APP_VERSION=0.8.1
      - GIT_SHA=dev
      - IMAGE=shvin/telemetry-api
      - UPDATE_CHECK_ENABLED=true
      - ADMIN_TOKEN=dev-only-token  # Only for development
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:80/v1/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ../../data:/data:ro

  # Optional: Watchtower for automatic updates (production)
  # Uncomment to enable auto-updates
  # watchtower:
  #   image: containrrr/watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --cleanup --interval 60 telemetry-api
  #   environment:
  #     - WATCHTOWER_POLL_INTERVAL=60
