name: Build & (on tag) Push Docker image

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Logging in to Docker Hub as $DOCKERHUB_USERNAME"
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Extract metadata (tags, labels)
        id: meta
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api
          tags: |
            type=raw,value=commit-${{ github.sha }}
            type=ref,event=tag

      - name: Build (no push on main)
        if: github.ref_type != 'tag'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64
          tags: telemetry-api:commit-${{ github.sha }}

      - name: Build & Push (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "Building and pushing image: $DOCKERHUB_USERNAME/telemetry-api:${{ github.ref_name }}"
          docker build -t "$DOCKERHUB_USERNAME/telemetry-api:${{ github.ref_name }}" .
          docker push "$DOCKERHUB_USERNAME/telemetry-api:${{ github.ref_name }}"
