name: Docker CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # for GHCR mirror; safe to keep
    env:
      IMAGE_NAME: telemetry-api
    steps:
      - uses: actions/checkout@v4

      - name: Validate Docker Hub secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "::error::Missing DOCKERHUB_USERNAME or DOCKERHUB_TOKEN"
            exit 1
          fi
          echo "Will push to Docker Hub: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Echo who we are and try a pull (soft)
        run: |
          echo "Logged in as: ${{ secrets.DOCKERHUB_USERNAME }}"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:nonexistent || true

      - name: Extract version
        id: ver
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=v0.4.0" >> $GITHUB_OUTPUT
          fi

      - name: Build & push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.ver.outputs.VERSION }}
